Repository hp-potion/vsc-gameboy, pull requests merged in 2023-11, with the labels that each got.

#2 feat: Compile TypeScript and Implement Dynamic Addition of WebView Sidebar Icons
  resources/dark/tetris.svg
  resources/light/tetris.svg
  src/extension.ts
  src/game/tetris/board.js
  src/game/tetris/constants.js
  src/game/tetris/main.js
  src/game/tetris/tetrisWeb.ts
  src/gameProvider.ts
  test.svg
Labels: feature

#6 TSC issue solved and move static files into resource
  package.json
  resource/game/number-game/index.html
  resource/game/tetris/asset/sound/Dungeon_Theme.mp3
  resource/game/tetris/asset/sound/drop.mp3
  resource/game/tetris/asset/sound/finish.mp3
  resource/game/tetris/asset/sound/moves.mp3
  resource/game/tetris/asset/sound/multimove.mp3
  resource/game/tetris/asset/sound/points.mp3
  resource/game/tetris/board.js
  resource/game/tetris/constants.js
  resource/game/tetris/index.html
  resource/game/tetris/main.js
  resource/game/tetris/piece.js
  resource/game/tetris/share-image-large.png
  resource/game/tetris/sound.js
  resource/game/tetris/styles.css
  src/extension.ts
  src/game/tetris/asset/share-image.png
  src/util/get-html-content.ts
  tsconfig.json
Labels: bug, feature

#8 Release v0.1.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  README.md
  docs/CONTRIBUTING.md
  docs/installation.mp4
  logo.png
  package.json
  resource/game/number-game/index.html
  resource/game/tetris/asset/sound/Dungeon_Theme.mp3
  resource/game/tetris/asset/sound/drop.mp3
  resource/game/tetris/asset/sound/finish.mp3
  resource/game/tetris/asset/sound/moves.mp3
  resource/game/tetris/asset/sound/multimove.mp3
  resource/game/tetris/asset/sound/points.mp3
  resource/game/tetris/board.js
  resource/game/tetris/constants.js
  resource/game/tetris/index.html
  resource/game/tetris/main.js
  resource/game/tetris/piece.js
  resource/game/tetris/share-image-large.png
  resource/game/tetris/sound.js
  resource/game/tetris/styles.css
  resource/icon/activity-bar-icon.svg
  resource/icon/dark/tetris-dark.svg
  resource/icon/light/tetris-light.svg
  src/extension.ts
  src/game-provider.ts
  src/game/meta-data.ts
  src/game/number-game/index.ts
  src/game/number-game/numbergame.ts
  src/test/runTest.ts
  src/test/suite/extension.test.ts
  src/test/suite/index.ts
  src/util/compile-ts-file.ts
  src/util/get-html-content.ts
  test.svg
  tsconfig.json
Labels: release

#10 chore: Supported from version 1.80.0 of VSCode
  package.json
Labels: chore

#11 Update CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: documentation

#12 feat: create intro video panel
  resource/extension/intro.mp4
  src/extension.ts
  src/util/create-intro-panel.ts
Labels: feature, PLATFORM

#15 docs: a new issue template - Create feature_suggestion.yml
  .github/ISSUE_TEMPLATE/feature_suggestion.yml
Labels: documentation

#16 style: Add prettier
  .prettierrc.json
  src/extension.ts
  src/game-provider.ts
  src/game/meta-data.ts
  src/test/runTest.ts
  src/test/suite/index.ts
Labels: documentation

#13 Add game webview test code by returning separate metadata to utility …
  .gitignore
  src/extension.ts
  src/test/suite/extension.test.ts
  src/util/compile-ts-file.ts
  src/util/create-intro-panel.ts
  src/util/create-webview-panel.ts
  src/util/get-html-content.ts
Labels: test

#21 feature: add star-crusade
  resource/game/star-crusade/assets/achievement.wav
  resource/game/star-crusade/assets/background.jpeg
  resource/game/star-crusade/assets/explosion.wav
  resource/game/star-crusade/assets/laser.wav
  resource/game/star-crusade/assets/ship.png
  resource/game/star-crusade/assets/soundtrack.mp3
  resource/game/star-crusade/game.js
  resource/game/star-crusade/index.html
  src/game/meta-data.ts
Labels: GAME

#27 feat: Implement Game Score Sidebar and Score Storage(GlobalStorage in VSC) Infrastructure with Score Transmission Logic
  package.json
  resource/game/tetris/main.js
  src/extension.ts
  src/score-board-provider.ts
  src/util/get-html-content.ts
  src/util/handle-panel-message.ts
  src/util/save-score.ts
Labels: feature, PLATFORM

#25 infra: Use SWC builder
  .swcrc
  package-lock.json
  package.json
Labels: chore, PLATFORM

#28 docs: Integrate 'Related Issues' Field into Issue Template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_suggestion.yml
Labels: documentation

#30 Simplified Chinese translation for contributing guide
  docs/CONTRIBUTING.md
  docs/translations/CONTRIBUTING.zh_cn.md
Labels: documentation

#35 Star-crusade Game Fixed an error where the game did not reload when pressing the R key
  resource/game/star-crusade/game.js
Labels: bug, GAME

#34 fix: to get icon path from metadata
  src/game-provider.ts
Labels: bug, feature, PLATFORM

#33 fix: watch option blocks build local extension while there is no change
  package.json
Labels: bug, chore

#36 fix: Update scoreboard immediately after game ends
  src/extension.ts
  src/score-board-provider.ts
  src/util/handle-panel-message.ts
Labels: feature, PLATFORM

#37 Feature: Game - add Suika like game
  resource/game/suika-game/assets/base/00_cherry.png
  resource/game/suika-game/assets/base/01_strawberry.png
  resource/game/suika-game/assets/base/02_grape.png
  resource/game/suika-game/assets/base/03_gyool.png
  resource/game/suika-game/assets/base/04_orange.png
  resource/game/suika-game/assets/base/05_apple.png
  resource/game/suika-game/assets/base/06_pear.png
  resource/game/suika-game/assets/base/07_peach.png
  resource/game/suika-game/assets/base/08_pineapple.png
  resource/game/suika-game/assets/base/09_melon.png
  resource/game/suika-game/assets/base/10_watermelon.png
  resource/game/suika-game/fruits.js
  resource/game/suika-game/index.html
  resource/game/suika-game/index.js
  resource/game/suika-game/styles.css
  resource/icon/dark/suika.svg
  resource/icon/dark/tetris.svg
  resource/icon/light/suika.svg
  resource/icon/light/tetris.svg
  src/game/meta-data.ts
Labels: feature, GAME

#38 feat: star-crusade add score-borad
  resource/game/star-crusade/game.js
Labels: feature

#42 add jest lib,vscode/test-cli and settings for testing libraries
  .vscode-test.js
  jest.config.js
  package-lock.json
  package.json
  src/util/add-score-script.ts
  src/util/get-html-content.ts
Labels: chore, test

#44 feat: Add test code for multiple vscode versions
  .vscode-test.js
  jest.config.js
  package-lock.json
  package.json
  src/test/runTest.ts
Labels: chore, PLATFORM, test

#45 test: test code of save-score
  src/test/suite/save-score.test.ts
Labels: GAME, test

#46 ci for testing
  .github/workflows/main-ci.yml
  package-lock.json
  package.json
  src/util/add-score-script.spec.ts
Labels: chore, PLATFORM, test

#48 feat: test mocha with swc
  package-lock.json
  package.json
Labels: feature, chore, test

#49 Feature: Game - add star-crusade game icon
  resource/icon/dark/star-crusade.svg
  resource/icon/light/star-crusade.svg
Labels: GAME

#50 package json update for minor updates
  logo.png
  package.json
Labels: documentation, chore

#52 Create user info and set to globalState
  package-lock.json
  resource/game/star-crusade/game.js
  resource/game/suika-game/index.js
  resource/game/tetris/main.js
  src/extension.ts
  src/test/suite/extension.test.ts
  src/test/suite/get-html-content.test.ts
  src/util/add-score-script.spec.ts
  src/util/add-score-script.ts
  src/util/get-html-content.ts
Labels: feature, PLATFORM

#53 feat: Add game 'mine sweeper'
  resource/game/mine-sweeper/assets/d0.png
  resource/game/mine-sweeper/assets/d1.png
  resource/game/mine-sweeper/assets/d2.png
  resource/game/mine-sweeper/assets/d3.png
  resource/game/mine-sweeper/assets/d4.png
  resource/game/mine-sweeper/assets/d5.png
  resource/game/mine-sweeper/assets/d6.png
  resource/game/mine-sweeper/assets/d7.png
  resource/game/mine-sweeper/assets/d8.png
  resource/game/mine-sweeper/assets/d9.png
  resource/game/mine-sweeper/assets/face-lose.png
  resource/game/mine-sweeper/assets/face.png
  resource/game/mine-sweeper/assets/flag.png
  resource/game/mine-sweeper/assets/mine.png
  resource/game/mine-sweeper/index.html
  resource/game/mine-sweeper/index.js
  resource/game/mine-sweeper/style.css
  src/game/meta-data.ts
Labels: feature, GAME

#54 feat: add global Score Board
  package-lock.json
  package.json
  src/extension.ts
  src/global-score-board-provider.ts
  src/score-board-provider.ts
  src/util/get-global-score.ts
  src/util/handle-panel-message.ts
Labels: PLATFORM

#56 update package json to release 0.4.0
  package-lock.json
  package.json
  src/extension.ts
Labels: release, PLATFORM

#57 update: change get globalScoreBoard method await
  src/util/handle-panel-message.ts
Labels: PLATFORM
